library(shiny)
library(bslib)
library(bsicons)
library(magrittr)
library(shinyWidgets)
library(shinydashboard)
library(shinyjs)
library(plotly)
library(DESeq2)
library(dplyr)
library(tidyverse)
library(heatmaply)
library(reshape2)
library(S4Vectors)
library(jsonlite)
library(pheatmap)
library(RColorBrewer)
library(shinydlplot)
library(survival)
library(readxl)
library(ggpubr)
library(shinyalert)
library(Glimma)

options(shiny.plot.res=96)


